### ISSUE TITLE
Installation via package managers

### ISSUE THREAD

**Issue by zeljkobekcic** [iits-consulting/otc-auth#25]
I would like to be able to install it with brew on the macos.

- Brew for MacOS
- APT for Debian based distros
- RPM for redhat based distros
- AUR for archlinux based distros
- more to be added

**Comment by Ninja243** [comment]
Looks like otc-auth is already on arch: https://aur.archlinux.org/packages?O=0&K=otc-auth

**Comment by Ninja243** [comment]
Might also be a good idea to add otc-auth to WinGet: https://learn.microsoft.com/en-us/windows/package-manager/package/ and Chocolatey: https://docs.chocolatey.org/en-us/create/create-packages

**Comment by Ninja243** [comment]
According to the Homebrew maintainers, this software is currently [too niche](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff). We can't add otc-auth to homebrew/core but are encouraged to set up our own tap
