### ISSUE TITLE
Requesting scoped token on login leads to loop

### ISSUE THREAD

**Issue by jotabe87** [iits-consulting/otc-auth#26]
When logging in, otc auth requests a scoped token right away (doesn't seem to be wanted behavior), and it does that in a loop:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/3001729/233079350-1f472cac-0ab3-4dae-8677-6ce12df82cb1.png">

We should fix it to request scoped tokens only when necessary, and only once.

**Comment by victorgetz** [comment]
this is not a bug but a feature see #22
