### ISSUE TITLE
otc-auth openstack config-create broken

### ISSUE THREAD

**Issue by bbung** [iits-consulting/otc-auth#37]
Version: OTC-Auth 2.0.0 (2023-06-09T16:06:28Z

> otc-auth openstack config-create --region eu-de 
Results in:
unknown arguments --region eu-de

> otc-auth openstack config-create            
-> fatal: --region not provided.

Please make sure the argument --region is provided or the environment variable REGION is set.

That doesn't seem right.

**Comment by victorgetz** [comment]
Hi sorry for the late response. We were busy last week.

You are right. Region should not be mandatory when creating the openstack config. We will fix it ASAP
