### ISSUE TITLE
Problem with secu_admin role is not inside the scoped token for eu_de

### ISSUE THREAD

**Issue by victorgetz** [iits-consulting/otc-auth#41]
I discovered when you use the terraform with the top level project like this:

```hcl
provider "opentelekomcloud" {
  cloud = "${var.os_domain_name}_${var.region}_${var.context}"
}

module "vaultkeys_bucket" {
  source      = "registry.terraform.io/iits-consulting/project-factory/opentelekomcloud//modules/obs_restricted"
  version     = "5.4.0"
  bucket_name = "${var.context}-${var.stage}-vaultkeys"
  providers   = {
    opentelekomcloud = opentelekomcloud.top_level_project
  }
  tags = local.tags
}
```

I will give some error since the scoped token for eu-de does not include the _secu_admin_ role.

If i use the unscoped token it works but i get problems with KMS Key creation.
If i use AK/SK everything works perfect.

**Comment by Ninja243** [comment]
We've solved the issue by just using temporary keys.

**Comment by bbung** [comment]
Hey @Ninja243 ,

i am running in the same issue as @victorgetz . Could you please share how you are using this with terraform an temporary access keys? I cannot get it to work properly. 

Many thanks!

**Comment by victorgetz** [comment]
We switched completly to temp AK/SK and since then everything works like a charm since months.

https://github.com/iits-consulting/otc-terraform-template/blob/main/otc-cloud/dev/providers.tf

inside the terraform template project everything is already adjusted to temp ak/sk you can take a look how it works there @bbung
