### ISSUE TITLE
Validate if SAML MFA works

### ISSUE THREAD

**Issue by victorgetz** [iits-consulting/otc-auth#5]
During our talk there was a question if we Support SAML MFA

**Comment by jotabe87** [comment]
As far as I know the problem with MFA + SAML is that the flow is currently SP-initialized. We've tried to change it to be IdP-initialized, but we were stuck on some problems. In my experience we could:

1. Try and see if the TOTP token can be sent through the current SP-initialized flow, similarly to what we do to username and password at the moment
2. Try and change the flow to be IdP-initialized. This would then be similar to how the OIDC flow is implemented and the IdP would completely take care of MFA. This is also safer than currently sending Basic Auth through the SP-initiated request.
